### ISSUE TITLE
ways to write less css but do more

### ISSUE THREAD

**Issue by argyleink** [danny45-crypto/Stark-Landing-Page#1]
from out office hours today for the featured collections

```css
.featured-collection {
    display: flex;
    gap: 20px;
    height: 300px;

    > * {
        background-repeat: no-repeat;
        background-size: contain;
        padding: 1.2rem;
        background-color: var(--fifth-color);
    }
}

.fourth-item-one {
    background-image: url(./Images/library_collection_Collection_Boundless_Disability_Employment_c297d236d9.png);
}

.fourth-item-two {
    background-image: url('./Images/library_collection_making_accessible_color_combos_42c8d90a99.png');
    background-color: var(--fifth-color);
}

.fourth-item-three {
    background-image: url('./Images/library_collection_Inclusive_Social_Media_b9669e6d39.png');
}
```
